const container = document.querySelector("#container");
const content = document.createElement("div");
const redEl = document.createElement("p");
const blueH3 = document.createElement("h3");
const newDiv = document.createElement("div");
const newH1 = document.createElement("h1");
const lastP = document.createElement("p");
content.classList.add("content");
content.textContent = "This is the glorious text-content!";
container.appendChild(content);
redEl.textContent = "Hey I am red!";
redEl.style.color = "red";
container.appendChild(redEl);
blueH3.textContent = "I am a blue h3!";
blueH3.style.color = "blue";
container.appendChild(blueH3);
newDiv.style.border = `1px solid black`;
newDiv.style.backgroundColor = "pink";
newH1.textContent = "I am in a div";
lastP.textContent = "ME TOO!";
newDiv.appendChild(newH1);
newDiv.appendChild(lastP);
container.appendChild(newDiv);
